### ISSUE TITLE
Generalize for per-project folder usage?

### ISSUE THREAD

**Issue by DivineDominion** [localauthor/zk#1]
The beauty of your approach with grep etc is that one needs very little to make this work. This got me thinking: I use `[[wiki links]]` in some statically generated website projects, too. Only not using an ID but the file name. But that's not the point -- wouldn't your package be able to use `project.el` or `projectile.el` (or toggle via `.dir-locals.el`) to even support multiple folders?

My elisp is not up to your level, so I'll have to ask instead of figuring this out by reading the code :)

If my interpretation is true, your package would be immensely useful to maintain any wiki-like folder of text files. The clickable buttons/links provide the glue while the markup language is up to the user. 

I don't want to suggest you change your package to _do_ this. Just curious if that's something it could also be doing relatively easily.

**Comment by localauthor** [comment]
Hey, thanks for checking this out! Big fan of the Archive, etc., if that wasn't obvious :)

I think you're right! I haven't played around with it, but I think it would be sufficient to set `zk-directory` as a directory-local variable to `default-directory`.

My elisp is only up to the level it took the write this package, so maybe this isn't a great way off doing things, but: if you add `.dir-locals.el` with `((nil . ((eval . (setq-local zk-directory default-directory)))))` to whatever directory you're working with, I think most things should fall into place.

I'm not very familiar with the ins and outs of directory-local variables, so, again, maybe there's a better way to do this. Anything come to mind?

At the very least, you'd want to mark this setting as 'safe' in your config, to keep Emacs from warning you about the dir-local variable the time.

I don't use `project.el` or `projectile.el`, so I'm not sure what it would take to integrate zk there.  Any thoughts on that?
