### ISSUE TITLE
searching grep style for notes

### ISSUE THREAD

**Issue by AtomicNess123** [localauthor/zk#10]
One of the functions I miss in Zetteldeft is to be able to search within content of notes on the fly (showing matches as I type keywords within my notes). Is this possible in your package? What kinds of search possiblities do you implement? Thanks.

**Comment by localauthor** [comment]
If you have consult installed and you load `zk-consult.el`, you can use the function `zk-consult-grep` to search your notes in the way you describe. 

Note that this is a change I just pushed a few second ago, so you'll have to have the latest version of `zk-consult.el`. Let me know if it works for you!

**Comment by AtomicNess123** [comment]
Thanks! So do I understand correctly that your package does everything that Zetteldeft does without relying on deft? Does it do the graph analysis of the notes as well?

**Comment by localauthor** [comment]
There is no support for graph analysis in zk, no.

And I haven't done a function-by-function comparison with Zetteldeft, so I can't say exactly how the two packages align.

If there are functions you feel are missing, please let me know, or feel free to contribute them in a PR. It could be a good exercise, trying to port some Zetteldeft functions into zk! :)

**Comment by localauthor** [comment]
Closed via 89fb5b1
