### ISSUE TITLE
[Help] need explanation how to use zk-index

### ISSUE THREAD

**Issue by poulpoulsen** [localauthor/zk#12]
hello,
i try to use your package and some commands works as expected, some unfortunately don't. perhaps i do not understand how to use it.

if i call zk-index, then i got an error:
file-name-extension: Wrong type argument: stringp, nil

could you pls explain how i have to use zk-index and zk-index-desktop?

Rergards
Poul

**Comment by localauthor** [comment]
Thank you for checking out zk-index!

Have you already followed the setup instructions for `zk`? See here: https://github.com/localauthor/zk#setup

It seems that you may not have set the variable `zk-file-extension`, but that’s just a guess.

It also might be helpful to watch this video demo of zk-index: https://youtu.be/7qNT87dphiA

I’m currently rewriting the README to include instructions for zk-index, but hopefully this gets you started in the meantime. Let me know if the issue persists!

**Comment by poulpoulsen** [comment]
hello,
thanks for the quick answer.
here is my config.
`
(require 'zk)
(require 'zk-index)
(zk-setup-auto-link-buttons)
(zk-setup-embark)
(zk-index-setup-embark)
;;(setq zk-tag-grep-function #'zk-consult-grep-tag-search)
;;(setq zk-grep-function #'zk-consult-grep)
(setq zk-directory "/home/held/Dokumente/zk/")
(setq zk-file-extension "org")
(setq zk-search-function 'lgrep)
;;(setq zk-tag-search-function 'zk-consult-grep-tag-search)
(setq zk-link-insert-title t)
(setq zk-default-backlink t)
(setq zk-index-desktop-directory "/home/held/Dokumente/zk/")
(setq zk-file-name-separator "--")
(add-hook 'completion-at-point-functions #'zk-completion-at-point 'append)
(let ((map global-map))
     (define-key map (kbd "<f12> n") #'zk-new-note)
     (define-key map (kbd "<f12> s") #'zk-search)
     (define-key map (kbd "<f12> d") #'dnn-org-datetree-find-create)
;;     (define-key map (kbd "C-c C-g n") #'org-gtd-show-all-next)
;;     (define-key map (kbd "C-c C-g s") #'org-gtd-show-stuck-projects)
)
`
the variable is set correctly i think.
`zk-file-extension is a variable defined in ‘zk.el’.
Its value is "org"
Original value was nil
`
any further ideas?
regards
Poul

**Comment by poulpoulsen** [comment]
btw:
creating, searching notes works.

**Comment by localauthor** [comment]
Could you do `M-x toggle-debug-on-error` and call `zk-index`, and then paste the backtrace here?

**Comment by poulpoulsen** [comment]
Hello,
here is the backtrace.
hope it helps :-)
`
Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  file-name-nondirectory(nil)
  file-name-extension(nil)
  (let ((fn (if (commandp 'eaf-open) #'(lambda (file) (eaf-open file)) orig-fn)) (ext (file-name-extension file))) (if (eaf--find-file-ext-p ext) (apply fn file nil) (apply orig-fn file args)))
  eaf--find-file-advisor(#f(compiled-function (filename &optional wildcards) "Edit file FILENAME.\nSwitch to a buffer visiting file FILENAME,\ncreating one if none already exists.\nInteractively, the default if you just type RET is the current directory,\nbut the visited file name is available through the minibuffer history:\ntype \\[next-history-element] to pull it into the minibuffer.\n\nThe first time \\[next-history-element] is used after Emacs prompts for\nthe file name, the result is affected by `file-name-at-point-functions',\nwhich by default try to guess the file name by looking at point in the\ncurrent buffer.  Customize the value of `file-name-at-point-functions'\nor set it to nil, if you want only the visited file name and the\ncurrent directory to be available on first \\[next-history-element]\nrequest.\n\nYou can visit files on remote machines by specifying something\nlike /ssh:SOME_REMOTE_MACHINE:FILE for the file name.  You can\nalso visit local files as a different user by specifying\n/sudo::FILE for the file name.\nSee the Info node `(tramp)File name Syntax' in the Tramp Info\nmanual, for more about this.\n\nInteractively, or if WILDCARDS is non-nil in a call from Lisp,\nexpand wildcards (if any) and visit multiple files.  You can\nsuppress wildcard expansion by setting `find-file-wildcards' to nil.\n\nTo visit a file without any kind of conversion and without\nautomatically choosing a major mode, use \\[find-file-literally]." (interactive #f(compiled-function () #<bytecode -0xa4cdf0709a9cfbd>)) #<bytecode -0x8db9e6ef2cdc1fb>) nil)
  apply(eaf--find-file-advisor #f(compiled-function (filename &optional wildcards) "Edit file FILENAME.\nSwitch to a buffer visiting file FILENAME,\ncreating one if none already exists.\nInteractively, the default if you just type RET is the current directory,\nbut the visited file name is available through the minibuffer history:\ntype \\[next-history-element] to pull it into the minibuffer.\n\nThe first time \\[next-history-element] is used after Emacs prompts for\nthe file name, the result is affected by `file-name-at-point-functions',\nwhich by default try to guess the file name by looking at point in the\ncurrent buffer.  Customize the value of `file-name-at-point-functions'\nor set it to nil, if you want only the visited file name and the\ncurrent directory to be available on first \\[next-history-element]\nrequest.\n\nYou can visit files on remote machines by specifying something\nlike /ssh:SOME_REMOTE_MACHINE:FILE for the file name.  You can\nalso visit local files as a different user by specifying\n/sudo::FILE for the file name.\nSee the Info node `(tramp)File name Syntax' in the Tramp Info\nmanual, for more about this.\n\nInteractively, or if WILDCARDS is non-nil in a call from Lisp,\nexpand wildcards (if any) and visit multiple files.  You can\nsuppress wildcard expansion by setting `find-file-wildcards' to nil.\n\nTo visit a file without any kind of conversion and without\nautomatically choosing a major mode, use \\[find-file-literally]." (interactive #f(compiled-function () #<bytecode -0xa4cdf0709a9cfbd>)) #<bytecode -0x8db9e6ef2cdc1fb>) nil)
  find-file(nil)
  zk-find-file-by-id(t)
  zk-index()
  funcall-interactively(zk-index)
  call-interactively(zk-index record nil)
  command-execute(zk-index record)
  execute-extended-command(nil "zk-index" nil)
  funcall-interactively(execute-extended-command nil "zk-index" nil)
  call-interactively(execute-extended-command nil nil)
  command-execute(execute-extended-command)
`

**Comment by localauthor** [comment]
Oh, I see the problem now! You've set `zk-default-backlink` to t, but it should either be nil or  a single id, as a string.

For example `(setq zk-default-backlink "202012131012")`

**Comment by localauthor** [comment]
Also, `zk-search-function` `zk-link-insert-title` aren't variables defined by this package.

**Comment by poulpoulsen** [comment]
Wow, now it works. Thanks!
Ok, one last question:
could you pls describe in short how i could use zk-index-desktop?

Regards
Poul

**Comment by localauthor** [comment]
Good! 👍

About zk-desktop, here is a brief demo: https://youtu.be/7qNT87dphiA?t=599

Briefly though, when you are in `zk-index`, scroll to a note that you want to "send to the desktop" and press `d`.

You'll be asked to select or create a "ZK-Desktop" file (which is just a specially titled file in your `zk-directory`; the names of desktop files begin with the string set in `zk-index-desktop-basename`).

Then you'll be asked if you want to visit the ZK-Desktop. If you want to send more notes, type `n` and send more notes. Then press `D` and go to the desktop, where you'll find a list of all the notes that you sent there.

It's essentially a selected index, that you can reorder, add and remove from.

You can also type in it, like a normal buffer, but first you have to toggle `zk-index-desktop-edit-mode`, by the keybinding `C-+`. (Using the same keybinding again will toggle edit-mode off.)

**Comment by poulpoulsen** [comment]
ok, thank you for the explanation.
Will check that.
Regards
Poul
