### ISSUE TITLE
zk-links as org-links with descriptive names

### ISSUE THREAD

**Issue by mfxarc** [localauthor/zk#13]
How to have zk-links like org-links that has description as in:
[[url or path][Some title]]
I tried just changing the zk-link-and-title-format to "[[%i][%t]" but complained about regex error at (thing-at-point-looking-at zk-id-regexp)

**Comment by localauthor** [comment]
This isn't currently possible, and it's a bit outside the scope of `zk.el` itself, given that it would require implementing some org-specific functions.

There has been some interest in adding more integration with org-style links in a companion package, `zk-org.el`, started in #8. Maybe this could be part of that effort? What do you think, @jgru?

**Comment by jgru** [comment]
I think this is be doable by modifying `zk-link-regexp` (and maybe some code segments where this variable is used). 
Howerever, I am a bit hesitant to do further work on the reference PR.

**Comment by localauthor** [comment]
This is now possible with org-link support provided in `zk-org-link.el`.

See #17 for more details.
