### ISSUE TITLE
save new note; prompt a little unclear

### ISSUE THREAD

**Issue by poulpoulsen** [localauthor/zk#15]
hello,
if i want to save a new note,the prompt shows my home directory ~, but it is saved inside zk-directory, if i only push RET.
that is a little bit unclear. usually the prompt shows the directory i complete or i am in.
is this the correct behavior?

Regards
poul

**Comment by localauthor** [comment]
Hi Poul,

Sorry, but it's not exactly clear what you're referring to when you say 'the prompt'. Could you list the sequence of steps that lead to this behavior?

I only ask because the typical way of creating a new note,`zk-new-note`, should save the new file automatically, without prompting.

**Comment by poulpoulsen** [comment]
hello,
yes you are right:
"I only ask because the typical way of creating a new note,zk-new-note, should save the new file automatically, without prompting.
"
i will describe what i have done:

M-x zk-new-note
Note title "Test"
Link at point Yes
add newline Yes

then the prompt for save the file:
see picture.
file:///home/held/Bilder/Bildschirmfoto%20vom%202022-03-09%2019-30-58.jpg

hope it helps
Regards
Poul

**Comment by poulpoulsen** [comment]
Hmmh,
the photo again.

![Bildschirmfoto vom 2022-03-09 19-30-58](https://user-images.githubusercontent.com/8409515/157508389-c6b9295d-148a-4fba-8a41-724ea8a0ef39.jpg)

**Comment by poulpoulsen** [comment]
the prompt shows, that i'm in my home directory.

**Comment by localauthor** [comment]
Ah! The problem is that `zk-new-note` is trying to save the buffer where the link is inserted, but you're in the scratch buffer, which is not a saved file. So the prompt is Emacs asking where you want to save the scratch buffer.

I've pushed a fix so this won't happen. Let me know if it works.

**Comment by poulpoulsen** [comment]
Wonderful !
first check seems to be working great.

Thanks very much
Regards
Poul
