### ISSUE TITLE
how could is use zk-consult functions?

### ISSUE THREAD

**Issue by poulpoulsen** [localauthor/zk#16]
hello,
... a new problem

i try to load zk-consult, but my different options (require or load) gives error.
"not found"
how could i load the file or use the functions?

the readme do not explain it in detail...
To use, make sure Consult is loaded, then load zk-consult.el

Regards
Poul

**Comment by localauthor** [comment]
For now, you will need to manually download the zk-consult.el file and place it into a directory that is in your emacs load path. 

If you’re not familiar with this process, one way to do this is to put the following in your config file:

```elisp
(add-to-list 'load-path "~/.emacs.d/lisp/")
```

and then place the zk-consult.el file into the directory ~/.emacs.d/lisp

You should then be able to require or load it. 

For info on load-path see https://www.emacswiki.org/emacs/LoadPath

**Comment by poulpoulsen** [comment]
hello,
zk-consult is loaded.

but it seems that two variables for consult are documented wrong.
this seems to be the right ones.
Correct?

(setq zk-grep-function 'zk-consult-grep)
(setq zk-tag-grep-function 'zk-consult-grep-tag-search)

unfortunately the command zk-consult-grep does nothing. i can input any searchstring but no results at all.
how do i use it?

pls give a description.
 
Regards
poul

**Comment by localauthor** [comment]
Do you also get no results when you use `zk-search`?

**Comment by poulpoulsen** [comment]
No, with zk-search all works as expected.

**Comment by poulpoulsen** [comment]
hello,
i found the mistake.
the grep arguments for consult are not set properly. I don't know why.
it works in the past.
;;(setq consult-grep-args "grep --null --no-line-buffered --color=auto --smart-case --exclude-dir=.git --line-number -C1 -I -r .")
this settings should display one line before and after the grip hit.
bzw: do you know what parameter is wrong?


so sorry for the noise.
Regards
Poul

**Comment by localauthor** [comment]
> do you know what parameter is wrong?

I'm not too familiar with grep options, but a quick look at the man page suggests that two of your parameters aren't valid for grep: "--no-line-buffered" and "--smart-case" aren't listed there. Taking them out seems to fix things.

But then, the -C1 option doesn't seem optimal for this use case, because it puts non-matching lines into the minibuffer.

> so sorry for the noise. 

No worries! Thanks for checking out zk!

**Comment by poulpoulsen** [comment]
i will stay with the default options and test additional ones carefully.
for now i close the ticket.

Best regards
Poul
