### ISSUE TITLE
Error zk-index; since two days ago??

### ISSUE THREAD

**Issue by poulpoulsen** [localauthor/zk#18]
hello,
since two days ago, a call of zk-index brings the following error:
`Debugger entered--Lisp error: (wrong-type-argument stringp nil)
  propertize(nil invisible t)
  zk-index--format-candidates(("/home/held/Dokumente/zk/202203051445_Ebay_einstell..." "/home/held/Dokumente/zk/202203051448_Etsy_Shop_öff..." "/home/held/Dokumente/zk/202203051412_Rhododendron_..." "/home/held/Dokumente/zk/202003051300_inbox.org" "/home/held/Dokumente/zk/202203051913_Stühle_für_Ve..." "/home/held/Dokumente/zk/202203051926_Sekretär_Verk..." "/home/held/Dokumente/zk/202203061900_günstige_Mobi..." "/home/held/Dokumente/zk/202203081942_Heizen_mit_Kl..." "/home/held/Dokumente/zk/202203091940_Ytong_Gasbeto..." "/home/held/Dokumente/zk/202203111946_Nebula.org" "/home/held/Dokumente/zk/202203121122_Material_für_..." "/home/held/Dokumente/zk/202203101942_Fliesenformen..." "/home/held/Dokumente/zk/202203131734_Protokoll_übe..." "/home/held/Dokumente/zk/202203131858_quadratloch_b..." "/home/held/Dokumente/zk/202203131905_Personenschut..." "/home/held/Dokumente/zk/202203131907_FI-Schutz_PRC..." "/home/held/Dokumente/zk/202203131907_FI-Schutz_PRC..."))
  zk-index--format(("/home/held/Dokumente/zk/202203051445_Ebay_einstell..." "/home/held/Dokumente/zk/202203051448_Etsy_Shop_öff..." "/home/held/Dokumente/zk/202203051412_Rhododendron_..." "/home/held/Dokumente/zk/202003051300_inbox.org" "/home/held/Dokumente/zk/202203051913_Stühle_für_Ve..." "/home/held/Dokumente/zk/202203051926_Sekretär_Verk..." "/home/held/Dokumente/zk/202203061900_günstige_Mobi..." "/home/held/Dokumente/zk/202203081942_Heizen_mit_Kl..." "/home/held/Dokumente/zk/202203091940_Ytong_Gasbeto..." "/home/held/Dokumente/zk/202203111946_Nebula.org" "/home/held/Dokumente/zk/202203121122_Material_für_..." "/home/held/Dokumente/zk/202203101942_Fliesenformen..." "/home/held/Dokumente/zk/202203131734_Protokoll_übe..." "/home/held/Dokumente/zk/202203131858_quadratloch_b..." "/home/held/Dokumente/zk/202203131905_Personenschut..." "/home/held/Dokumente/zk/202203131907_FI-Schutz_PRC..." "/home/held/Dokumente/zk/202203131907_FI-Schutz_PRC...") nil)
  zk-index--sort(("/home/held/Dokumente/zk/202003051300_inbox.org" "/home/held/Dokumente/zk/202203051913_Stühle_für_Ve..." "/home/held/Dokumente/zk/202203051926_Sekretär_Verk..." "/home/held/Dokumente/zk/202203061900_günstige_Mobi..." "/home/held/Dokumente/zk/202203081942_Heizen_mit_Kl..." "/home/held/Dokumente/zk/202203091940_Ytong_Gasbeto..." "/home/held/Dokumente/zk/202203111946_Nebula.org" "/home/held/Dokumente/zk/202203121122_Material_für_..." "/home/held/Dokumente/zk/202203101942_Fliesenformen..." "/home/held/Dokumente/zk/202203131734_Protokoll_übe..." "/home/held/Dokumente/zk/202203131858_quadratloch_b..." "/home/held/Dokumente/zk/202203131905_Personenschut..." "/home/held/Dokumente/zk/202203131907_FI-Schutz_PRC..." "/home/held/Dokumente/zk/202203131907_FI-Schutz_PRC...") nil nil)
  zk-index()
  funcall-interactively(zk-index)
  call-interactively(zk-index nil nil)
  command-execute(zk-index)
`

do you know whats going on with this?
this command works correctly before??

btw: i update last zk version from melpa, but as far as i tested the other commands works...

Regards
Poul

**Comment by localauthor** [comment]
Could you check if the variable `zk-index-format` is set? It looks like it is nil

**Comment by localauthor** [comment]
Sorry, ignore that. I misread the backtrace.

It seems that the problem is at the `string-match` function in `zk-index--format-candidates`; it seems to be returning nil on the first item in the list, the file beginning `202203051445_Ebay_einstell...`?

Is that filename formatted correctly, so that it correlates with this regexp: `(concat "\\(?1:" zk-id-regexp "\\).\\(?2:.*?\\)\\." zk-file-extension ".*")`

**Comment by localauthor** [comment]
Here's a version of `zk-index--format-candidates` that adds a format checker, so if you evaluate this and run `zk-index` (after closing the ZK-Index buffer), it should tell you if a file is improperly formatted.

```elisp
(defun zk-index--format-candidates (&optional files format)
  "Return a list of FILES as formatted candidates, following FORMAT.

FORMAT must be a 'format-spec' template, wherein '%i' is replaced
by the ID and '%t' by the title. It can be a string, such as \"%t
[[%i]]\", or a variable whose value is a string. If nil,
'zk-completion-at-point-format' will be used by default.

FILES must be a list of filepaths. If nil, all files in
'zk-directory' will be returned as formatted candidates."
  (let* ((zk-index-format (if zk-index-invisible-ids "%t %i"
                            zk-index-format))
         (format (if format format
                   zk-index-format))
         (list (if files files
                 (zk--directory-files)))
         (output))
    (dolist (file list)
      (progn
        (string-match (concat "\\(?1:"
                              zk-id-regexp
                              "\\).\\(?2:.*?\\)\\."
                              zk-file-extension
                              ".*")
                      file)
        (unless (match-string 1 file)
          (error "Improper format: %s" file))
        (let ((id (if zk-index-invisible-ids
                      (propertize (match-string 1 file) 'invisible t)
                    (match-string 1 file)))
              (title (replace-regexp-in-string
                      zk-file-name-separator
                      " "
                      (match-string 2 file))))
          (when id
            (push (concat zk-index-prefix
                          (format-spec format
                                       `((?i . ,id)(?t . ,title))))
                  output)))))
    output))
```

**Comment by localauthor** [comment]
I've added a filter to `zk--directory-files` that it only lists files with the extension set in `zk-file-extension`.

This should fix the problem. Let me know if it persists.

Thanks for continuing to use zk, and for finding these issues!

**Comment by poulpoulsen** [comment]
> 

hello,
the variable is set:
is it ok?

zk-index-format is a variable defined in ‘zk-index.el’.

Its value is "%t [[%i]]"

Default format for candidates in the index.

  You can customize this variable.

**Comment by poulpoulsen** [comment]
i just update from melpa.
Yes, now it works!

thank you very much.
i will continue to use investigate and use your very useful package.

Regards
Poul

**Comment by poulpoulsen** [comment]
i think i close the ticket.
