### ISSUE TITLE
zk-index shows no items after update today; any related news about update details?

### ISSUE THREAD

**Issue by poulpoulsen** [localauthor/zk#19]
hello,
i just update zk today and unfortunately i got no list after command zk-index.
first call gives:
zk-index--format-candidates: Wrong type argument: stringp, nil

second call gives empty list.

Any clues whats wrong?

**Comment by localauthor** [comment]
So sorry for the bug! The latest commit reverts some recent changes that I think are to blame for the problems you found. Let me know if the problem persists.

**Comment by poulpoulsen** [comment]
Wonderful!
its working again.
Thank you for your fast response.
