### ISSUE TITLE
Howm with similar ideas maybe you are interested in

### ISSUE THREAD

**Issue by duzaichuan** [localauthor/zk#2]
[howm](https://howm.osdn.jp/) Do you know this project? It uses grep with links and backlinks. Also utilize simple plain texts and depends only on emacs. Maybe interesting to include it in your REAME related implementations.

**Comment by localauthor** [comment]
Thanks for bringing howm to my attention! I hadn't come across it before. Looks like it quite an extensive package, a bit beyond what zk is aiming for. Although I do see there are some similarities. 

If  you use howm, are there any features you think a package like zk might want to incorporate? I haven't had time to really check out its feature set.

In any case, thanks for the pointer!

**Comment by duzaichuan** [comment]
Indeed, howm is quite extensive and I neither use much features of howm. I started to use it just a couple months ago, to capture some small snippets of ideas and use its powerful search and links. These features I frequently use are well incorporated I believe (and enhanced in my opinion) in your zk package, which is more suitable in my daily usage.

Howm has been developed and maintained for a long time (ten years or so?). It seems that, however, not many people know about howm. Might be due to the language gap (most its tutorial is in Japenese). So, just bring it up here for people interested in.
