### ISSUE TITLE
 zk--grep-tag-list  should be limited to zk-file-extension

### ISSUE THREAD

**Issue by samspo** [localauthor/zk#20]
Hello,
Thanks for your nice package. 
zk--grep-tag-list searches in every files included in zk-directory
If you keep track of changes with git, the git files will be included in the search (and it will propose very strange tags)
Maybe the search should be limited to files with the zk-file-extension?

**Comment by localauthor** [comment]
Thanks for the suggestion! Let me know if the latest commit doesn't do what you expect.

**Comment by samspo** [comment]
It works.
Thanks!
