### ISSUE TITLE
Need help in bringing together ace-window link-hint zk

### ISSUE THREAD

**Issue by poulpoulsen** [localauthor/zk#21]
Hello,
I want to bring together, what you described in
https://localauthor.github.io/posts/aw-select.html

Gould you please describe, how i should do it?

The packages for own are working (ace-window, link-hint, zk)

Regards
Poul

**Comment by localauthor** [comment]
Certainly! It's a bit piecemeal, since it's not all together in one package but...

1. Download the following two files:

https://github.com/localauthor/.emacs.d/blob/main/my-lisp/link-hint-aw-select.el
https://github.com/localauthor/.emacs.d/blob/main/my-lisp/zk-link-hint.el

2. Put these files in a directory on your [load-path](https://www.emacswiki.org/emacs/LoadPath).

3. Add this to your `init.el` file:

```elisp
(require 'zk-link-hint)
(require 'link-hint-aw-select)

(with-eval-after-load 'link-hint-aw-select
  (link-hint-define-type 'zk-link
    :aw-select #'link-hint--aw-select-zk-link)
  (defun link-hint--aw-select-zk-link (id)
    (with-demoted-errors "%s"
      (if (> (length (aw-window-list)) 1)
          (let ((window (aw-select nil))
                (buffer (current-buffer))
                (new-buffer))
            (zk-follow-link-at-point id)
            (setq new-buffer
                  (current-buffer))
            (switch-to-buffer buffer)
            (aw-switch-to-window window)
            (switch-to-buffer new-buffer))
        (link-hint-open-link-at-point)))))
```

**Comment by poulpoulsen** [comment]
Thank you,
as far as i see it works.
I will play a bit with it and come back then.

Thanks again.
Poul

**Comment by localauthor** [comment]
Great! I'll leave this open then.

Let me know if you have issues/questions in the meantime.

**Comment by localauthor** [comment]
Hi @poulpoulsen, just checking in to see if you've had any success/problems with this issue, or any others.

**Comment by poulpoulsen** [comment]
hello,
ah yes, i bring it together. sorry for the delay.
i do not fully understand how it works, but it works :-)
have to learn a bit more about using ace.

regards
poul
