### ISSUE TITLE
links failed for IDs longer than 12 characters

### ISSUE THREAD

**Issue by XLramones** [localauthor/zk#24]
I have my zk-id-time-string-format set to %Y%m%d%H%M%S (14 digits), but when calling the zk-new-note function and inserting link, the console reports that  `Search failed: "\\[\\[\\([0-9]\\{12\\}\\)]]"`. 
I am not very competent in elisp, but is there anyway to aid this ?

**Comment by localauthor** [comment]
Yes! Per the docstring for zk-id-time-string-format, you'll need to alter zk-id-regexp appropriately. Try adding the following to your config:

(setq zk-id-regexp "\\([0-9]\\{14\\}\\)")

**Comment by XLramones** [comment]
Thank you! I am still having an issue with the zk-new-note function. whenever I call it with the option of  inserting the link at point, the same `Search failed: "\\[\\[\\([0-9]\\{12\\}\\)]]"` message is displayed and the note is not created, just a dead link is inserted.
notes created and linked to without the insert at point functionality work just fine.

**Comment by localauthor** [comment]
Oh I see the problem. You'll need to reset zk-link-regexp.

Adding this to your config should fix it:
(setq zk-link-regexp "\\[\\[\\([0-9]\\{12\\}\\)]]")


On Aug 13, 2022, 17:02 +0300, Josh Baillie ***@***.***>, wrote:
	Thank you! I am still having an issue with the zk-new-note function. whenever I call it with the option of inserting the link at point, the same Search failed: "\\[\\[\\([0-9]\\{12\\}\\)]]" message is displayed and the note is not created, just a dead link is inserted.
notes created and linked to without the insert at point functionality work just fine.

**Comment by XLramones** [comment]
thank you so much
