### ISSUE TITLE
Make add-link-at-point default unless universal prefix

### ISSUE THREAD

**Issue by lesliesrussell** [localauthor/zk#25]
I may be overlooking it but I can't find a way to make add-link-at-point the default with no prompt. If I set this as default behavior, zk should not prompt and simply add a link at point, unless the note creation is preceded by C-u.

This would more closely mirror other emacs behaviors

**Comment by localauthor** [comment]
Do you have zk-new-note-link-insert set to t?

**Comment by lesliesrussell** [comment]
Thank you. That is what I was missing.
