### ISSUE TITLE
zk-new-note-header "format" should be defvar

### ISSUE THREAD

**Issue by lesliesrussell** [localauthor/zk#26]
format is hard coded in zk-new-note-header and should be a configurable variable. This would allow org-mode users to place tags in a property drawer along with other org-mode info.

**Comment by localauthor** [comment]
The configurable variable is zk-new-note-header-function, which you can set to a function that will insert whatever text you want at the top of a new file.

**Comment by lesliesrussell** [comment]
Thank you, that is what I have done but it really should be a var there might be users who are not capable

**Comment by localauthor** [comment]
What would the different possible values of a variable be, in this case, if not functions? It's not clear exactly what you have in mind.

**Comment by lesliesrussell** [comment]
The result of default new note is
`===
zk--link-and-title orig-id
===`

It would be easier for most to have those _===_ wrappers be configurable as customizable variables. That would allow non coding org-mode users and others to configure the front matter with less headache. 

So for example org-mode users might want to wrap time clock logging or deadline information in the front matter.

I have it doing what I need, just making a suggestion. Awesome work btw!

**Comment by localauthor** [comment]
Could you post the function you're using?

**Comment by lesliesrussell** [comment]
All I am trying to say is expose the format string as a configurable variable.

```
(defun my-new-note-header (title new-id &optional orig-id)
  "Insert header in new notes with args TITLE and NEW-ID.
Optionally use ORIG-ID for backlink."
  (insert (format "* %s\n:id:\n%s\n:end:" title new-id))
  (when (ignore-errors (zk--parse-id 'title orig-id)) ;; check for file
    (progn
      (insert ":id:\n<- ")
      (zk--insert-link-and-title orig-id (zk--parse-id 'title orig-id))
      (newline)
      ))
      ;; (insert ":end:\n\n")
      )`
`
```
