### ISSUE TITLE
zk-new-note

### ISSUE THREAD

**Issue by uwejochum** [localauthor/zk#47]
Since the latest update zk-new-note produces "Wrong type argument: stringp, nil" on Emacs 27.1 (build 1, x86_64-pc-linux-gnu, GTK+ Version 3.24.30, cairo version 1.16.0) on Linux Mint.
The "Message" buffer has this: "helm-M-x-execute-command: Wrong type argument: stringp, nil", but uncommenting helm does not eliminate the problem of not being able to create a new zk-note.
Despite all that: Thanks for zk!

**Comment by localauthor** [comment]
Are you trying to create a note from a non-file-visiting buffer (like the scratch buffer), by chance?

**Comment by localauthor** [comment]
I've just pushed a commit; could you see if that fixes the issue?

**Comment by uwejochum** [comment]
Sorry for my late answer: Yes, you are right, I was in a
non-file-visiting buffer. When I am in a zk-buffer, zk-new-note works as
expected.

I’ll try the new version with the new commit in a few minutes.

Thanks,

Uwe

Grant Rosson schrieb am Donnerstag, den 03.November 2022:

> Are you trying to create a note from a non-file-visiting buffer (like the scratch buffer), by chance?


Grant Rosson schrieb am Donnerstag, den 03.November 2022:

> Are you trying to create a note from a non-file-visiting buffer (like the scratch buffer), by chance?

**Comment by uwejochum** [comment]
Wunderbar, that fixes the issue!

Thanks a lot, with best wishes from Lake Konstanz (Germany),

Uwe

Grant Rosson schrieb am Donnerstag, den 03.November 2022:

> I've just pushed a commit; could you see if that fixes the issue?

**Comment by localauthor** [comment]
Great! Thanks for reporting the issue. Hope zk keeps working for you!
