### ISSUE TITLE
Case insensitive index focussing

### ISSUE THREAD

**Issue by jgru** [localauthor/zk#7]
Dear Grant, 

I am missing a case insensitive version of `zk-index-focus`. 
I thought it might be easy to add a `(case-fold-search t)` statement to `zk--directory-files` but this was not successful. 
Any hints on where I should make the modification for focusing in a case insensitive manner?

Thanks in advance. 

Best regards,
jgru

**Comment by localauthor** [comment]
This was a fun one ;)

It's bothered me for a while, but didn't really get to it yet, so thanks for the push.

Let me know if this works.

**Comment by jgru** [comment]
> This was a fun one ;)
> 
> It's bothered me for a while, but I had avoided looking into it too much, so thanks for the push.
> 
> Let me know if this works.

Thanks very much! Works flawlessly! 
Seeing the solution with `zk--id-list` seems obvious now..

**Comment by localauthor** [comment]
The real solution is in querying `zk--alist` instead of `directory-files`, since the latter is pretty inflexible, I guess.

**Comment by jgru** [comment]
> 



> The real solution is in querying `zk--alist` instead of `directory-files`, since the latter is pretty inflexible, I guess.
> 

Eventually good to know for future tinkering. 

> Glad it works!

Thanks again!
