### ISSUE TITLE
Do you have any screenshot or short video to show up?

### ISSUE THREAD

**Issue by yibie** [localauthor/zk#80]
I'm very interested in zk and zk-lumman. 

But I can't understand the workflow by description. 

If you have any screenshot will very helpful, and short video will be better.

At last, thank you for your great work.

**Comment by localauthor** [comment]
Check these out (from the readme), and let me know if they're helpful:

[zk - Setup and Main Features](https://www.youtube.com/watch?v=BixlUK4QTNk)
[zk - Getting Started - Hydra and Inbox Note](https://www.youtube.com/watch?v=oEgdJlojlU8)
[zk-index and zk-desktop](https://www.youtube.com/watch?v=7qNT87dphiA)
[zk-luhmann](https://www.youtube.com/watch?v=O6iSV4pQQ5g)
